[supabase]
url = "https://bolnfpvnnpbookmpmtuy.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvbG5mcHZubnBib29rbXBtdHV5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTM1MjUwNywiZXhwIjoyMDU2OTI4NTA3fQ.9kxX97BbVGy_TjOJtVvEMkPtmVGt4KuVzHKTjCVZ3bk"